add Fbuild
git-svn-id: http://fe.baidu.com/repos/doc/sdcfe@81171 01db0846-df26-4232-8c27-33e78907c97d

diff --git a/tools/bin/Fbuild b/tools/bin/Fbuild
--- a/tools/bin/Fbuild
+++ b/tools/bin/Fbuild
@@ -7,4 +7,8 @@ if [ "${OSTYPE}" = "cygwin" -a "${TERM}" != "xterm" ]; then
    exit
 fi
 
-exec node "Fbuild.js" "$@"
+[ -f "Fbuild.js" ] && {
+  exec node "Fbuild.js" "$@"
+} || {
+  echo "Can't find Fbuild.js in current directory"
+}
